# Step 1: Use an official Python image as a base
FROM python:3.9-slim

# Step 2: Set working directory
WORKDIR /dbi/db_init

# Step 3: Install dependencies
RUN pip install --no-cache-dir psycopg2

# Step 4: Install PostgreSQL client to check if the db is running
RUN apt-get update && apt-get install -y postgresql-client

# Step 5: Copy the Python script into the container
COPY ../dbi/init_sql.py /dbi/db_init/

# Step 6: Expose PostgreSQL port
EXPOSE 5432

# Step 7: Command to run the script on container start
CMD ["python", "create_tables.py"]
